mixed-port: 7890
redir-port: 7892
tproxy-port: 7893

allow-lan: true
mode: rule
log-level: info

external-controller: 127.0.0.1:9090

dns:
  enable: true

proxies: []

proxy-groups: []

rules:
  - MATCH,DIRECT